name: pullrequest
on: 
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-on-pullrequest:
    runs-on: ubuntu-latest
    steps:
    - name: echo
      run: echo "Pull request was triggered"